apiVersion: v1
kind: Service
metadata:
  name: sample-k8s-guestbook
  labels:
    service: sample-k8s-guestbook
spec:
  ports:
    - port: 8080
  selector:
    service: sample-k8s-guestbook
    tier: service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-k8s-guestbook-service
  labels:
    service: sample-k8s-guestbook
spec:
  selector:
    matchLabels:
      service: sample-k8s-guestbook
      tier: service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: sample-k8s-guestbook
        tier: service
    spec:
      containers:
        - image: sample-k8s-service:latest
          name: sample-k8s-guestbook-service
          env:
            - name: DB_URL
              value: jdbc:postgresql://sample-k8s-guestbook-dbms:5432/guestbook
            - name: DB_USER
              value: guestbook
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-pass
                  key: password
          ports:
            - containerPort: 8080
