/*
 * This file is generated by jOOQ.
 */
package com.g0dkar.samplek8sproj.persistence.jooq.tables.records;


import com.g0dkar.samplek8sproj.persistence.jooq.tables.Messages;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessagesRecord extends UpdatableRecordImpl<MessagesRecord> implements Record6<UUID, Boolean, OffsetDateTime, UUID, String, Integer> {

    private static final long serialVersionUID = -270599891;

    /**
     * Setter for <code>public.messages.id</code>.
     */
    public MessagesRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.messages.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.messages.active</code>.
     */
    public MessagesRecord setActive(Boolean value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.messages.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.messages.created</code>.
     */
    public MessagesRecord setCreated(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.messages.created</code>.
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.messages.parent</code>.
     */
    public MessagesRecord setParent(UUID value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.messages.parent</code>.
     */
    public UUID getParent() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.messages.message</code>.
     */
    public MessagesRecord setMessage(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.messages.message</code>.
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.messages.visitor_type_id</code>.
     */
    public MessagesRecord setVisitorTypeId(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.messages.visitor_type_id</code>.
     */
    public Integer getVisitorTypeId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, Boolean, OffsetDateTime, UUID, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, Boolean, OffsetDateTime, UUID, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Messages.MESSAGES.ID;
    }

    @Override
    public Field<Boolean> field2() {
        return Messages.MESSAGES.ACTIVE;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return Messages.MESSAGES.CREATED;
    }

    @Override
    public Field<UUID> field4() {
        return Messages.MESSAGES.PARENT;
    }

    @Override
    public Field<String> field5() {
        return Messages.MESSAGES.MESSAGE;
    }

    @Override
    public Field<Integer> field6() {
        return Messages.MESSAGES.VISITOR_TYPE_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public Boolean component2() {
        return getActive();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreated();
    }

    @Override
    public UUID component4() {
        return getParent();
    }

    @Override
    public String component5() {
        return getMessage();
    }

    @Override
    public Integer component6() {
        return getVisitorTypeId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public Boolean value2() {
        return getActive();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreated();
    }

    @Override
    public UUID value4() {
        return getParent();
    }

    @Override
    public String value5() {
        return getMessage();
    }

    @Override
    public Integer value6() {
        return getVisitorTypeId();
    }

    @Override
    public MessagesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public MessagesRecord value2(Boolean value) {
        setActive(value);
        return this;
    }

    @Override
    public MessagesRecord value3(OffsetDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public MessagesRecord value4(UUID value) {
        setParent(value);
        return this;
    }

    @Override
    public MessagesRecord value5(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public MessagesRecord value6(Integer value) {
        setVisitorTypeId(value);
        return this;
    }

    @Override
    public MessagesRecord values(UUID value1, Boolean value2, OffsetDateTime value3, UUID value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessagesRecord
     */
    public MessagesRecord() {
        super(Messages.MESSAGES);
    }

    /**
     * Create a detached, initialised MessagesRecord
     */
    public MessagesRecord(UUID id, Boolean active, OffsetDateTime created, UUID parent, String message, Integer visitorTypeId) {
        super(Messages.MESSAGES);

        set(0, id);
        set(1, active);
        set(2, created);
        set(3, parent);
        set(4, message);
        set(5, visitorTypeId);
    }
}
