/*
 * This file is generated by jOOQ.
 */
package com.g0dkar.samplek8sproj.persistence.jooq.tables.records;


import com.g0dkar.samplek8sproj.persistence.jooq.tables.VisitorTypeEnum;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VisitorTypeEnumRecord extends UpdatableRecordImpl<VisitorTypeEnumRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1642605512;

    /**
     * Setter for <code>public.visitor_type_enum.id</code>.
     */
    public VisitorTypeEnumRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.visitor_type_enum.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.visitor_type_enum.name</code>.
     */
    public VisitorTypeEnumRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.visitor_type_enum.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return VisitorTypeEnum.VISITOR_TYPE_ENUM.ID;
    }

    @Override
    public Field<String> field2() {
        return VisitorTypeEnum.VISITOR_TYPE_ENUM.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public VisitorTypeEnumRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public VisitorTypeEnumRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public VisitorTypeEnumRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VisitorTypeEnumRecord
     */
    public VisitorTypeEnumRecord() {
        super(VisitorTypeEnum.VISITOR_TYPE_ENUM);
    }

    /**
     * Create a detached, initialised VisitorTypeEnumRecord
     */
    public VisitorTypeEnumRecord(Integer id, String name) {
        super(VisitorTypeEnum.VISITOR_TYPE_ENUM);

        set(0, id);
        set(1, name);
    }
}
